addSbtPlugin("com.github.sbt"            % "sbt-ci-release"   % "1.5.12")
addSbtPlugin("org.jetbrains"             % "sbt-ide-settings" % "1.1.0")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"     % "2.5.2")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"     % "2.4.6")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"    % "2.0.9")
addSbtPlugin("com.timushev.sbt"          % "sbt-rewarn"       % "0.1.3")
addSbtPlugin("com.timushev.sbt"          % "sbt-updates"      % "0.6.4")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"     % "0.4.4")